12 mustafa1
infotech-class-3/class-3-homeworks pull request #315
Opened 2023-06-04 11:33 UTC by Mustafadagda

## Description

## Checklist
- [ ] Pull request basligi, '00-Alex - html ödev' seklinde düzenlendi
- [ ] Tüm degisiklikler yapildi ve Pull Request review icin hazir

2023-06-04 11:34 UTC, Mustafadagda commented
mustafa

2023-06-06 11:40 UTC, adolsoft requested changes
.vscode klasorunu githup göndermeye gerek yok. Silebilirisn.
2023-05-15 klasorun içinde 23-06-28 klasoru var bu klasör düzgün yerdemi 
Klasör yapısını kontrol edebilirmisin

2023-06-08 20:51 UTC, adolsoft requested changes
.vscode gorunuyor

2023-06-08 20:56 UTC, adolsoft submitted a review, later dismissed

2023-06-08 21:02 UTC, adolsoft approved these changes

2023-06-08 21:03 UTC, closed without merging